### PR TITLE
Functionality/Documentation update

### PR DESCRIPTION
**Pull request by jrb467**
I've been using this for a project and it was missing some functionality, so I went ahead and added it. I updated the README while I was at it

### CODE REVIEW

**Comment by dominictarr** [comment]
this is great work, can I add you as a collaborator so you can merge this your self? Also what is your npm username? (so I can add you as an npm owner?)

**Comment by jrb467** [comment]
Sure!  And my npm username is jrb467

**Comment by dominictarr** [comment]
cool, you are now a collaborator so you have commit access and can publish new npm versions!

**Comment by dominictarr** [comment]
feel free to merge this!

**Pull request merged**
